// Generated by CoffeeScript 1.9.3
define(function(require, module, exports) {
  var _frag, _id, addClipPath, addLinearGradient, addShadowFilter, ensureRange, getId, newSVG;
  _id = 0;
  _frag = document.createDocumentFragment();
  getId = function() {
    return _id += 1;
  };
  ensureRange = function(num, min, max) {
    if (max !== null) {
      if (num > max) {
        num = max;
      }
    }
    if (min !== null) {
      if (num < min) {
        num = min;
      }
    }
    return num;
  };
  newSVG = function() {
    return d3.select(_frag).append('svg').remove();
  };
  addClipPath = function(svg, id) {
    return svg.append('defs').append('clipPath').attr('id', id);
  };
  addShadowFilter = function(svg, id, rgba) {
    var feMerge, filter;
    if (rgba == null) {
      rgba = [.5, .5, .5, 1];
    }
    filter = svg.append('defs').append('filter').attr({
      id: id,
      width: 1.4,
      height: 1.4,
      x: -.2,
      y: -.1
    });
    filter.append('feColorMatrix').attr({
      type: 'matrix',
      values: ("0 0 0 " + rgba[0] + " 0 ") + ("0 0 0 " + rgba[1] + " 0 ") + ("0 0 0 " + rgba[2] + " 0 ") + ("0 0 0 " + rgba[3] + " 0 ")
    });
    filter.append('feGaussianBlur').attr({
      stdDeviation: 1,
      result: 'blur'
    });
    filter.append('feOffset').attr({
      'in': 'blur',
      dx: 0,
      dy: 1,
      result: 'offsetBlur'
    });
    feMerge = filter.append('feMerge');
    feMerge.append('feMergeNode').attr('in', 'offsetBlur');
    return feMerge.append('feMergeNode').attr('in', 'SourceGraphic');
  };
  addLinearGradient = function(svg, id, stop0, stop1) {
    var gradient;
    if (stop1 == null) {
      stop1 = 'white';
    }
    gradient = svg.append('defs').append('linearGradient').attr({
      id: id,
      x1: 0,
      y1: -.5,
      x2: 0,
      y2: 1
    });
    gradient.append('stop').attr('offset', 0).style('stop-color', stop0);
    return gradient.append('stop').attr('offset', 1).style('stop-color', stop1);
  };
  return {
    getId: getId,
    ensureRange: ensureRange,
    newSVG: newSVG,
    addClipPath: addClipPath,
    addShadowFilter: addShadowFilter,
    addLinearGradient: addLinearGradient
  };
});
